<a href="https://colab.research.google.com/github/sgcortes/KerasTensor/blob/master/03_Numpy_Refresher_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>



<img src='https://learnopencv.com/wp-content/uploads/2022/01/c4_01_NumPy_logo.png' width=200 align='left'><br/>

## Table of Contents

* [1 Element-Wise Operations](#1-Element-Wise-Operations)
* [2 Linear Algebra](#2-Linear-Algebra)
* [3 Array Statistics](#3-Array-Statistics)

In [ ]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations. 

In [ ]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.21041253 0.88755839 0.66489539 0.94373668]
 [0.70727984 0.36836865 0.6982336  0.50269374]
 [0.26232185 0.52228445 0.05247682 0.05716847]
 [0.47625445 0.79862503 0.63162816 0.66867585]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.91024727 0.25631975 0.67886272 0.04316317]
 [0.36117935 0.17528051 0.28984292 0.76483188]
 [0.22307419 0.22657289 0.438016   0.40286254]
 [0.27880113 0.92810432 0.75433858 0.35863441]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [ ]:
a + 5 # Element wise scalar addition.

array([[5.21041253, 5.88755839, 5.66489539, 5.94373668],
       [5.70727984, 5.36836865, 5.6982336 , 5.50269374],
       [5.26232185, 5.52228445, 5.05247682, 5.05716847],
       [5.47625445, 5.79862503, 5.63162816, 5.66867585]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [ ]:
a - 5 # Element wise scalar subtraction.

array([[-4.78958747, -4.11244161, -4.33510461, -4.05626332],
       [-4.29272016, -4.63163135, -4.3017664 , -4.49730626],
       [-4.73767815, -4.47771555, -4.94752318, -4.94283153],
       [-4.52374555, -4.20137497, -4.36837184, -4.33132415]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [ ]:
a * 10 # Element wise scalar multiplication.

array([[2.10412529, 8.87558392, 6.64895389, 9.43736678],
       [7.07279836, 3.6836865 , 6.98233597, 5.02693737],
       [2.62321853, 5.22284445, 0.52476824, 0.57168465],
       [4.76254455, 7.98625026, 6.31628158, 6.68675846]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [ ]:
a/10 # Element wise scalar division.

array([[0.02104125, 0.08875584, 0.06648954, 0.09437367],
       [0.07072798, 0.03683686, 0.06982336, 0.05026937],
       [0.02623219, 0.05222844, 0.00524768, 0.00571685],
       [0.04762545, 0.0798625 , 0.06316282, 0.06686758]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [ ]:
a + b # Element wise array/vector addition.

array([[1.1206598 , 1.14387814, 1.34375811, 0.98689985],
       [1.06845918, 0.54364916, 0.98807652, 1.26752561],
       [0.48539605, 0.74885733, 0.49049282, 0.460031  ],
       [0.75505558, 1.72672935, 1.38596673, 1.02731026]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [ ]:
a - b # Element wise array/vector subtraction.

array([[-0.69983474,  0.63123864, -0.01396734,  0.90057351],
       [ 0.34610049,  0.19308814,  0.40839068, -0.26213814],
       [ 0.03924766,  0.29571156, -0.38553917, -0.34569407],
       [ 0.19745333, -0.12947929, -0.12271042,  0.31004143]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [ ]:
a * b # Element wise array/vector multiplication.

array([[0.19152743, 0.22749875, 0.4513727 , 0.04073466],
       [0.25545487, 0.06456785, 0.20237806, 0.38447619],
       [0.05851724, 0.1183355 , 0.02298569, 0.02303103],
       [0.13278028, 0.74120734, 0.47646149, 0.23981017]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [ ]:
a / b # element wise array/vector division

array([[ 0.23115975,  3.46269995,  0.97942539, 21.8643983 ],
       [ 1.95825106,  2.10159499,  2.40900693,  0.65726044],
       [ 1.17593993,  2.30514978,  0.11980572,  0.14190564],
       [ 1.70822285,  0.86049058,  0.83732713,  1.86450552]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [ ]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.21041253 0.88755839 0.66489539 0.94373668]
 [0.70727984 0.36836865 0.6982336  0.50269374]
 [0.26232185 0.52228445 0.05247682 0.05716847]
 [0.47625445 0.79862503 0.63162816 0.66867585]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.01925351 0.8175445  0.78584274 0.50314486]
 [0.93917021 0.75638215 0.33138527 0.4441472 ]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "/var/folders/__/9cnms5ms0gz3wk9_cz4ctxqr0000gn/T/ipykernel_19219/3053537578.py", line 10, in <module>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)` 

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array. 

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1
 
The examples below show how `B` is successfully broadcasted to `A` according to the rules above.
 
``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2

Array "b":
Array:
[0 1 0]
Data type:	int64
Array shape:	(3,)
Array Dim:	1

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2



## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

Array "a":
Array:
[[0.89042525 0.00185178 0.63485571]
 [0.45828996 0.39700786 0.74523715]]
Data type:	float64
Array shape:	(2, 3)
Array Dim:	2

Transose of "a":
Array:
[[0.89042525 0.45828996]
 [0.00185178 0.39700786]
 [0.63485571 0.74523715]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = np.matmul(a,b) 

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be 
                                                          # same for matrix multiplication

Array "a":
Array:
[[0.6558135  0.44199714 0.2873197  0.92405359]
 [0.3087299  0.18971711 0.75472795 0.29666377]
 [0.42034068 0.77374161 0.35020636 0.32808625]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.7266519  0.41308904]
 [0.26073966 0.53704643]
 [0.76897388 0.10513026]
 [0.55644044 0.62232665]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

matrix multiplication of a and b:
Array:
[[1.32691644 1.11355153]
 [1.01924774 0.49338635]
 [0.95904648 0.8301674 ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2

(3, 4) x (4, 2) --> (3, 2)


### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [ ]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
c = a@b 
array_info(c)

Array "a":
Array:
[[0.91184197 0.99647478 0.71448849 0.97777114]
 [0.30830991 0.53614134 0.82528076 0.89638653]
 [0.57088338 0.53093183 0.48706807 0.81887126]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.36932614 0.77824974]
 [0.52367608 0.28492496]
 [0.80329695 0.50109414]
 [0.85338901 0.58182426]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

Array:
[[2.26696265 1.92047829]
 [1.82254324 1.32778495]
 [1.57895448 1.3160717 ]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html?highlight=matrix%20inverse" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.91980067 0.88840414 0.30798564]
 [0.44189709 0.15825762 0.36623873]
 [0.11574711 0.57521542 0.48989421]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

Inverse of "A" ("A_inverse"):
Array:
[[ 0.65110184  1.26206564 -1.35283764]
 [ 0.85139173 -2.02933564  0.98185457]
 [-1.15350783  2.0845821   1.20803459]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

"A x A_inverse = Identity" should be true:
Array:
[[ 1.00000000e+00  8.50868268e-17 -1.31287266e-16]
 [-9.46459746e-17  1.00000000e+00 -9.00679422e-17]
 [-1.27856568e-17 -2.72579233e-17  1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2



### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot%20product" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b) 
array_info(dot_prod)

Array:
[1 2 3 4]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
[5 6 7 8]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
70
Data type:	int64
Array shape:	()
Array Dim:	0



## 3 Array Statistics

### 3.1 Sum

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### 3.2 Sum Along Axis

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array:
[[1 2 3]
 [4 5 6]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2


sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


### 3.3 Minimum and Maximum

In [ ]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### 3.4 Min and Max along Axis

In [ ]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array:
[[-2  0  4]
 [ 1  2  3]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2

a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


### 3.5 Mean and Standard Deviation

In [ ]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [ ]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))  
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))   

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
