<h1 style=“font-size:30px;“>TensorFlow Assignment</h1>

Here, you have to implement Leaky ReLu, Sigmoid and Convolution, using TensorFlow, same as you did in the NumPy assignment.

### Maximum Points: 30

<div>
    <table>
        <tr><td><h3>Section</h3></td> <td><h3>Problem</h3></td> <td><h3>Points</h3></td> </tr>
        <tr><td><h3>1</h3></td> <td><h3>Leaky ReLU Implementation</h3></td> <td><h3>5</h3></td> </tr>
        <tr><td><h3>2</h3></td> <td><h3>Sigmoid Implementation</h3></td> <td><h3>10</h3></td> </tr>
        <tr><td><h3>3</h3></td> <td><h3>Convolution Implementation</h3></td> <td><h3>15</h3></td> </tr>
    </table>
</div>

In [ ]:
from typing import Tuple

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

In [ ]:
block_plot = False

## 1 Leaky ReLU [5 Points]

<img src='https://learnopencv.com/wp-content/uploads/2022/02/c4_01_leaky_relu.png' width=600 align=‘center’><br/>

This is how you implement **Leaky ReLU**:


$$
f(x) = \left\{
  \begin{array}\\
  x\alpha&\mbox{if }x<0\\
  x&\mbox{otherwise}\\
  \end{array}
\right\}
$$

For the following input:

$$
x = [-0.7329559\;1.23146666]\;,\alpha=0.03
$$

LeakyReLU will return:

$$
[-0.02198867\;1.2314667]
$$

In [ ]:
def leaky_relu(in_tensor: tf.Tensor, alpha: tf.float32) -> tf.Tensor:

    """
    leaky_relu

    x >= 0 -> f(x) = x
    x < 0 -> f(x) = alpha * x

    Parameters

    array: Input array.
    alpha: Slope for the activation
            when input is negative.

    Returns:

    Returns an array having same shape as input.
    """

    indices = tf.where(in_tensor < 0)
    values = tf.gather_nd(in_tensor, indices=indices)
    ###
    ### YOUR CODE HERE
    ###
    result = tf.tensor_scatter_nd_update(in_tensor, indices, updates)

    return result

In [ ]:
inTensor = tf.constant([-0.7329559, 1.23146666])
outTensor = leaky_relu(inTensor, 0.03)

print(f"Input tensor: {inTensor}")
print(f"Result: {outTensor}")

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## 2 Sigmoid [10 Points]

<img src='https://learnopencv.com/wp-content/uploads/2022/02/c4_01_sigmoid.png' width=600 align=‘center’>

Next, we implement **Sigmoid**:


$$\frac{1}{1 + e^{-x}}$$


For the given input:

$$
[-2.39537836\;-0.09620075]
$$

Sigmoid returns:

$$
[0.08352581\;0.47596836]
$$

In [ ]:
def sigmoid(in_tensor: tf.Tensor) -> tf.Tensor:

    """
    sigmoid

    f(x) = 1 / (1 + e^-x)

    Parameters

    array: Input array.

    Returns

    Returns an array having the same shape as input array.
    """
    sig_cal = None
    
    ###
    ### YOUR CODE HERE
    ###
    
    return sig_cal

In [ ]:
inTensor = tf.constant([-2.39537836, -0.09620075])
outTensor = sigmoid(inTensor)

print(f"Input tensor: {inTensor}")
print(f"Result: {outTensor}")

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


## 3 The Convolution Operation [10 Points]

Today, Convolutional Neural Networks (CNNs) are among the most widely-used architectures in the field of Computer Vision. One of the most fundamental operations performed in CNNs is the **Convolution Operation**.

**Now, what is a convolution operation?**

A convolution operation is the element-wise multiplication, of a "kernel" (or filter) with a region of an input image, followed by a summing operation, performed iteratively on the whole image.

This illustration will make things more clear. Assume that your input is a 2D array, of size `5 x 5`, having the following values:


\begin{bmatrix}
7 & 2 & 3 & 3 & 8\\
4 & 5 & 3 & 8 & 4\\
3 & 3 & 2 & 8 & 4\\
2 & 8 & 7 & 2 & 7\\
5 & 4 & 4 & 5 & 4
\end{bmatrix}

And the kernel is of size `3 x 3`, with values:

\begin{bmatrix}
1 & 0 & -1 \\
1 & 0 & -1 \\
1 & 0 & -1 \\
\end{bmatrix}

The convolution operation of this kernel with the 2D input array is summarized in the followinf steps.

### **Step 1:**
<img src = 'https://learnopencv.com/wp-content/uploads/2022/01/c4_01_cnn_conv_step_1.jpg' width=800 align='center'><br/>

### **Step 2:**
<img src = 'https://learnopencv.com/wp-content/uploads/2022/01/c4_01_cnn_conv_step_2.jpg' width=800 align='center'><br/>

### **Step 3:**
<img src = 'https://learnopencv.com/wp-content/uploads/2022/01/c4_01_cnn_conv_step_3.jpg' width=800 align='center'><br/>

### **Step 4:**
<img src = 'https://learnopencv.com/wp-content/uploads/2022/01/c4_01_cnn_conv_step_4.jpg' width=800 align='center'><br/>

In the above figures, **`*`** represents the convolution operation. Continue these series of operations untill we get the final output, as shown below: 

<img src = 'https://learnopencv.com/wp-content/uploads/2022/01/c4_01_cnn_conv_output.jpg' width=200 align='center'><br/>
     

In general, the size of the output after the Convolution operation is given by the formula:

$$\lfloor{\frac{n + 2p - k}{s}}\rfloor + 1$$ 

where `n` = Input shape, `p` = padding , `k`= kernel_size and `s` = stride;


**Note: For this assignment, you need not worry about the padding and stride. We have kept them at `0` and `1` respectively.**

**So, here, the output shape is given by: $$n - k + 1$$**

Taking the above example as a reference, we have `n = 5` and `k = 3`. Therefore, the output shape is given by:
`5 - 3 + 1 = 3`. Thus the output shape is a `3 x 3` square matrix.

In the following section, you will be implementing the Convolution operation.

**Again, to simplify things for you, we will be dealing only with square matrices  here.**


For this, you may find the [tensor_scatter_nd_update](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update), [reduce_sum](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum), [multiply](https://www.tensorflow.org/api_docs/python/tf/math/multiply) and [expand_dims](https://www.tensorflow.org/api_docs/python/tf/expand_dims) functions useful.

In [ ]:
def convolve(
    in_tensor: tf.Tensor,
    kernel: tf.Tensor,
    verbose: bool = False,
) -> tf.Tensor:

    """
    convolve

    Parameters

    input_array: Array on which convolution is done.
    output_image: Placeholder array for output.
    kernel: Kernel/ Filter.
    
    Returns

    Convolved array.
    """
    
    inshape = in_tensor.shape
    kshape = kernel.shape
    
    output_array = tf.zeros((inshape[0] - kshape[0] + 1, inshape[1] - kshape[1] + 1), dtype=tf.int32)

    for i in range(0, inshape[0]):
        for j in range(0, inshape[1]):
            try:
                ###
                ### YOUR CODE HERE
                ###
            
            except Exception as exception:
                if verbose:
                    print("Warn: Image boundary is ignored.")
                    raise exception

    return output_array

**Running the code cell below, you should get the following output:**

```
Output array:
tf.Tensor(
[[ 6 -9 -8]
 [-3 -2 -3]
 [-3  0 -2]], shape=(3, 3), dtype=int32)
 
```

In [ ]:
kernel = tf.constant([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

input_array = tf.constant([[7,2,3,3,8],[4,5,3,8,4],[3,3,2,8,4],[2,8,7,2,7],[5,4,4,5,4]])
ouput_array = convolve(input_array, kernel)

print(f"Output array:")
print(ouput_array)

In [ ]:
###
### AUTOGRADER TEST - DO NOT REMOVE
###


### 4 Applications of CNNs

CNNs are excellent for determining the spatial information of the input images, such as edges, gradients etc. We will use the above `convolve()` function to show you how it can determine both vertical and horizontal edges of a given input image. To generate the vertical edges of an image, we place high values on one vertical half and low values on the other.

In [ ]:
def create_vertical_edge_image(dsize: Tuple = (64, 64)) -> tf.Tensor:

    """
    create_vertical_edge_image

    A vertical edged test image is created.
    For input dsize=(4, 4), the below array
    is returned.

    [255 255 0 0
     255 255 0 0
     255 255 0 0]

    Parameters
    ----------

    dsize: Shape of the image to create. The
    shape is of the form (height, width).

    Returns
    -------

    A numpy array with shape dsize
    """

    height, width = dsize
    zeros = tf.zeros((height, width // 2))
    whites = tf.ones(dsize) * 255
    indices = tf.where(zeros == 0)
    updates = tf.gather_nd(whites, indices=indices)
    result = tf.scatter_nd(indices, updates, dsize)

    return result

In [ ]:
input_image = tf.cast(create_vertical_edge_image(), tf.int32)

plt.imshow(input_image.numpy(), cmap="gray")
plt.show(block=block_plot)

In [ ]:
vertical_kernel = tf.constant([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

vertical_edge = convolve(input_image, vertical_kernel)

plt.imshow(vertical_edge.numpy(), cmap="gray")
plt.show(block=block_plot)

As you can see, we could successfully determine the vertical edges for the `test_image`. Now let’s use the convolution function to determine the horizontal edges as well. Similarly, to generate the horizontal edges of an  image, we will place high values on one horizontal half and low values on the other.

In [ ]:
def create_horizontal_edge_image(dsize: Tuple = (64, 64)) -> tf.Tensor:

    """
    create_vertical_edge_image

    A vertical edged test image is created.
    For input dsize=(4, 4), the below array
    is returned.

    [255 255 255 255
     255 255 255 255
     000 000 000 000
     000 000 000 000]

    Parameters
    ----------

    dsize: Shape of the image to create. The
    shape is of the form (height, width).

    Returns
    -------

    A numpy array with shape dsize
    """

    height, width = dsize
    zeros = tf.zeros((width // 2, height))
    whites = tf.ones(dsize) * 255
    indices = tf.where(zeros == 0)
    updates = tf.gather_nd(whites, indices=indices)
    result = tf.scatter_nd(indices, updates, dsize)

    return result

In [ ]:
input_image = tf.cast(create_horizontal_edge_image(), tf.int32)

plt.imshow(input_image.numpy(), cmap="gray")
plt.show(block=block_plot)

In [ ]:
horizontal_kernel = tf.constant([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])
horizontal_edge = convolve(input_image, horizontal_kernel)

plt.imshow(horizontal_edge.numpy(), cmap="gray")
plt.show(block=block_plot)